name = "Duckquill"
description = "Modern, pretty, and clean theme"
license = "MIT"
homepage = "https://codeberg.org/daudix/duckquill"
min_version = "0.17.2"
demo = "https://daudix.codeberg.page/duckquill"

[extra]
primary_color = "#9a9996"
primary_color_alpha = "rgba(154, 153, 150, 0.2)"
date_format = "%d %B %Y"
issues_url = ""
source_url = ""

[author]
name = "David Lapshin"
homepage = "https://daudix.codeberg.page"
